name: Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and run Docker container
      run: |
        docker build -t my-node-app .
        docker run -d --name my-node-container my-node-app

    
